### PR TITLE
Add <ruby> support for asian languages

### PR DESCRIPTION
**Pull request by Nekotekina**
Reformat ruby annotations in braces.
Before: `01day.01month.1999year`
After: `01.01.1999(daymonthyear)`
This is mainly intended for asian languages, Japanese for example, where current handling of ruby creates a mix of words and readings. With this patch, readings are put in braces after words, improving readability.

Rendered example:
image
Before:
`その言葉が表ひよう示じされた瞬しゆん間かん`
After:
`その言葉が表示(ひようじ)された瞬間(しゆんかん)`

EDIT: for more information about <ruby>: https://www.w3.org/TR/ruby/

### CODE REVIEW

**Comment by kevinboone** [comment]
Hi. Would you be kind enough to explain more about what this change does? I'm not sure what 'ruby' is in this context.

**Comment by axmonti** [comment]
I was confused by "ruby" vs. "Ruby" as well. Apparently, ruby annotations are small characters placed above or beside larger characters to indicate pronunciation or alternate readings. Those are visible in the rendered example above. If the annotations are not handled correctly, incorrect readings or missing information may result. Here's what @Nekotekina wrote:

Without Ruby annotations - 'The moment the words were revealed':

その言葉が表ひよう示じされた瞬しゆん間かん

Correct (with Ruby annotations) - 'The moment that word is displayed':

その言葉が表示(ひようじ)された瞬間(しゆんかん)

By including Ruby annotations as in-line text, the correct reading is clearly indicated.

As far as I can tell (and you likely know this from the code), the `inruby` flag detects that the text being read is part of a ruby annotation. When an `<rt>` tag is encountered, ruby annotations are accumulated in the `ruby` string until a closing `</rt>` flag is encountered. Once the closing tag is encountered, the `ruby` string is appended to `para`, enclosed in parentheses. 

No idea if this affects conversion in other languages - I didn't test this at all.

**Comment by Nekotekina** [comment]
Oh yeah, thanks for the explanation. I forgot to link important information about <ruby> tags in HTML.
https://www.w3.org/TR/ruby/
It shows many examples.

**Comment by kevinboone** [comment]
Thank you for this enhancement. I have merged it although, to be honest, I don't know enough about <rt> to be able to test it comprehensively. But it doesn't seem to break anything else, and it only adds about 15 lines to the code :)

**Pull request merged**
